[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Health check configuration
[healthcheck]
path = "/health"
port = "3000"
timeout = 60
interval = 120
initialDelay = 5